<script setup lang="ts">
import { ref } from 'vue'
import {
	ContributionGraph,
	StatsBreakdown,
	generateDummyStats,
	ColorScheme,
	ExperienceEntry,
} from 'git-stats-components/vue'
import 'git-stats-components/style.css'

// Save dummy data for testing
const dummyData = generateDummyStats({
	username: 'demo-user',
	platform: 'github',
	projectCount: 42,
	commitCount: 3200,
})

// In a real app, this would be generated by GitHub Actions
// For this demo, we'll use the dummy data
if (typeof window !== 'undefined') {
	localStorage.setItem('git_stats_cache', JSON.stringify(dummyData))
}

const currentColorScheme = ref<ColorScheme>('green')

const experienceData: ExperienceEntry[] = [
	{
		startDate: '2020-01-01',
		endDate: null,
		skills: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js'],
	},
	{
		startDate: '2018-06-01',
		endDate: '2020-01-01',
		skills: ['JavaScript', 'jQuery', 'PHP'],
	},
]

function handleDayClick(data: { date: string; count: number }) {
	console.log('Day clicked:', data)
	alert(`${data.count} contributions on ${data.date}`)
}

function handleColorSchemeChange(scheme: ColorScheme) {
	console.log('Color scheme changed:', scheme)
	currentColorScheme.value = scheme
}
</script>

<template>
	<div class="app">
		<header class="header">
			<h1>🎨 Vue Git Stats Demo</h1>
			<p>Beautiful contribution graphs for Vue 3</p>
		</header>

		<main class="main">
			<section class="section">
				<h2>📊 Contribution Graph</h2>
				<p class="description">
					GitHub-style contribution heatmap with
					{{ totalContributions }} contributions
				</p>

				<ContributionGraph
					data-url="/data/git-stats.json"
					:color-scheme="currentColorScheme"
					:show-settings="true"
					@day-click="handleDayClick"
					@color-scheme-change="handleColorSchemeChange"
				/>
			</section>

			<section class="section">
				<h2>📈 Stats Breakdown</h2>
				<p class="description">
					Project counts, commits, and years of experience
				</p>

				<StatsBreakdown
					data-url="/data/git-stats.json"
					:experience-data="experienceData"
					:show-custom-stat="true"
				>
					<template #icon-custom>🚀</template>
					<template #custom-stat-label>Rocket Fuel Consumed</template>
				</StatsBreakdown>
			</section>

			<section class="section code-section">
				<h2>💻 Usage</h2>
				<pre><code>&lt;script setup&gt;
    import { ContributionGraph, StatsBreakdown } from 'git-stats-components'
    import 'git-stats-components/style.css'
    
    const experienceData = [
      {
        startDate: '2020-01-01',
        endDate: null,
        skills: ['JavaScript', 'Vue', 'TypeScript']
      }
    ]
    &lt;/script&gt;
    
    &lt;template&gt;
      &lt;ContributionGraph 
        data-url="/data/git-stats.json"
        color-scheme="green"
        @day-click="handleClick"
      /&gt;
      
      &lt;StatsBreakdown 
        data-url="/data/git-stats.json"
        :experience-data="experienceData"
      /&gt;
    &lt;/template&gt;</code></pre>
			</section>
		</main>

		<footer class="footer">
			<p>
				Made with ❤️ using
				<a
					href="https://github.com/derekjj/git-stats-components"
					target="_blank"
					>git-stats-components</a
				>
			</p>
		</footer>
	</div>
</template>

<style scoped>
.app {
	min-height: 100vh;
	background: linear-gradient(135deg, #0d1117 0%, #1a1e26 100%);
	color: #e6edf3;
}

.header {
	text-align: center;
	padding: 60px 20px 40px;
	background: rgba(255, 255, 255, 0.02);
	border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.header h1 {
	font-size: 48px;
	margin: 0 0 12px 0;
	background: linear-gradient(135deg, #39d353 0%, #58a6ff 100%);
	-webkit-background-clip: text;
	-webkit-text-fill-color: transparent;
}

.header p {
	font-size: 18px;
	color: #7d8590;
	margin: 0;
}

.main {
	max-width: 1200px;
	margin: 0 auto;
	padding: 40px 20px;
}

.section {
	margin-bottom: 60px;
}

.section h2 {
	font-size: 32px;
	margin: 0 0 8px 0;
	color: #e6edf3;
}

.description {
	color: #7d8590;
	margin: 0 0 24px 0;
	font-size: 16px;
}

.code-section {
	background: rgba(255, 255, 255, 0.02);
	padding: 32px;
	border-radius: 12px;
	border: 1px solid rgba(255, 255, 255, 0.1);
}

.code-section pre {
	background: #161b22;
	padding: 20px;
	border-radius: 8px;
	overflow-x: auto;
	margin: 0;
}

.code-section code {
	font-family: 'Monaco', 'Courier New', monospace;
	font-size: 14px;
	line-height: 1.6;
	color: #e6edf3;
}

.footer {
	text-align: center;
	padding: 40px 20px;
	border-top: 1px solid rgba(255, 255, 255, 0.1);
	color: #7d8590;
}

.footer a {
	color: #58a6ff;
	text-decoration: none;
}

.footer a:hover {
	text-decoration: underline;
}

@media (max-width: 768px) {
	.header h1 {
		font-size: 32px;
	}

	.section h2 {
		font-size: 24px;
	}

	.code-section {
		padding: 20px;
	}
}
</style>
