import { useState } from 'react'
import {
	ContributionGraph,
	StatsBreakdown,
	generateDummyStats,
} from '@git-stats-components/react'
import '@git-stats-components/react/style.css'
import type { ColorScheme, ExperienceEntry } from '@git-stats-components/react'
import './App.css'

// Save dummy data for testing
const dummyData = generateDummyStats({
	username: 'demo-user',
	platform: 'github',
	projectCount: 42,
	commitCount: 3200,
})

// In a real app, this would be generated by GitHub Actions
if (typeof window !== 'undefined') {
	localStorage.setItem('git_stats_cache', JSON.stringify(dummyData))
}

const experienceData: ExperienceEntry[] = [
	{
		startDate: '2020-01-01',
		endDate: null,
		skills: ['JavaScript', 'TypeScript', 'React', 'Vue', 'Node.js'],
	},
	{
		startDate: '2018-06-01',
		endDate: '2020-01-01',
		skills: ['JavaScript', 'jQuery', 'PHP'],
	},
]

function App() {
	const [currentColorScheme, setCurrentColorScheme] =
		useState<ColorScheme>('green')

	const handleDayClick = (data: { date: string; count: number }) => {
		console.log('Day clicked:', data)
		alert(`${data.count} contributions on ${data.date}`)
	}

	const handleColorSchemeChange = (scheme: ColorScheme) => {
		console.log('Color scheme changed:', scheme)
		setCurrentColorScheme(scheme)
	}

	return (
		<div className="app">
			<header className="header">
				<h1>⚛️ React Git Stats Demo</h1>
				<p>Beautiful contribution graphs for React</p>
			</header>

			<main className="main">
				<section className="section">
					<h2>📊 Contribution Graph</h2>
					<p className="description">
						GitHub-style contribution heatmap
					</p>

					<ContributionGraph
						dataUrl="/data/git-stats.json"
						colorScheme={currentColorScheme}
						showSettings={true}
						onDayClick={handleDayClick}
						onColorSchemeChange={handleColorSchemeChange}
					/>
				</section>

				<section className="section">
					<h2>📈 Stats Breakdown</h2>
					<p className="description">
						Project counts, commits, and years of experience
					</p>

					<StatsBreakdown
						dataUrl="/data/git-stats.json"
						experienceData={experienceData}
						showCustomStat={true}
					/>
				</section>

				<section className="section code-section">
					<h2>💻 Usage</h2>
					<pre>
						<code>{`import { ContributionGraph, StatsBreakdown } from '@git-stats-components/react'
import '@git-stats-components/react/style.css'

const experienceData = [
  {
    startDate: '2020-01-01',
    endDate: null,
    skills: ['JavaScript', 'React', 'TypeScript']
  }
]

function App() {
  const handleDayClick = (data) => {
    console.log('Clicked:', data)
  }

  return (
    <>
      <ContributionGraph 
        dataUrl="/data/git-stats.json"
        colorScheme="green"
        onDayClick={handleDayClick}
      />
      
      <StatsBreakdown 
        dataUrl="/data/git-stats.json"
        experienceData={experienceData}
      />
    </>
  )
}`}</code>
					</pre>
				</section>
			</main>

			<footer className="footer">
				<p>
					Made with ❤️ using{' '}
					<a
						href="https://github.com/derekjj/git-stats-components"
						target="_blank"
						rel="noopener noreferrer"
					>
						@git-stats-components/react
					</a>
				</p>
			</footer>
		</div>
	)
}

export default App
